# Criando Dataframe (Curso)

**Autor:** Cristian Matias de Souza · **Projeto:** Exemplo1

Objetivo: Criando dataframe para analise.

In [1]:
import pandas as pd

In [2]:
dados = {
    'Nome': ['Alice', 'Bob', 'Charlie'],
    'Idade': [24, 30, 22],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']
}

In [5]:
# Exibindo os primeiros Dados
df = pd.DataFrame(dados)

df

      Nome  Idade          Cidade
0    Alice     24       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     22  Belo Horizonte

In [8]:
# Retornando as primeira linha
df.head(1)

    Nome  Idade     Cidade
0  Alice     24  São Paulo

In [10]:
# Exibindo as ultimas linhas
df.tail(1)

      Nome  Idade          Cidade
2  Charlie     22  Belo Horizonte