# 04 - Exploração: Criando Dataframe

**Objetivo:** Conceitos Estruturados da Criação de Dataframe e seus Metodos e Atributos.

**Perguntas que quero responder:**
1. Qual é o grão da tabela (uma linha representa o quê)?
2. A base tem qualidade suficiente para virar dashboard?
3. Quais colunas viram dimensão e quais viram métrica?
4. Que transformações precisam ir para `src/transform.py`?

**Autor:** Cristian | **Data:** 2026-09-13

> Este notebook é rascunho. O que sobreviver aqui vira função testada em `src/`.

In [21]:
from unittest.mock import inplace

import pandas as pd

In [22]:
# ==> Criando Dataframe
personagens_df = pd.DataFrame({
    'nome': ['Cristian', 'Jessica Fernanda', 'Bruna'],
    'idade' : [39, 36, 30],
    'peso': [96.5, 50.5, 60.6],
    'eh_jedi': [True, False, True]
})

In [23]:
personagens_df

               nome  idade  peso  eh_jedi
0          Cristian     39  96.5     True
1  Jessica Fernanda     36  50.5    False
2             Bruna     30  60.6     True

💡 Diferença rápida:
*   Método (.rename()): Executa uma ação ou transformação nos dados e exige parênteses.
* Atributo (ex: .shape, .columns): Apenas retorna uma propriedade ou informação sobre o objeto, sem executar uma ação, e não usa parênteses.

In [24]:
personagens_df_renomeado = personagens_df.rename(
    columns={
        'nome': 'Nome Completo',                        # Renomeando coluna com método rename()
        'idade': 'Idade'
    },
    inplace=True                                        # inplace é uma argumento que modifica o dataframe
)

In [25]:
personagens_df_renomeado

In [26]:
personagens_df

      Nome Completo  Idade  peso  eh_jedi
0          Cristian     39  96.5     True
1  Jessica Fernanda     36  50.5    False
2             Bruna     30  60.6     True